server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Gzip (optional, aber nett)
  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  # SPA: alle nicht gefundenen Pfade auf index.html umleiten,
  # damit Angular-Router Deep-Links handeln kann.
  location / {
    try_files $uri $uri/ /index.html;
  }
}
